;;; sync-merge-test.el --- Tests for sync reconciliation planner -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'sync-merge)

(ert-deftest org-rem-plan-mapped-missing-org-deletes-reminder ()
  (let* ((org-items nil)
         (reminders '((("external_id" . "RID-1")
                       ("last_modified" . "t1"))))
         (mappings '(((org_id . "ORG-1")
                      (org_hash . "h1")
                      (reminder_external_id . "RID-1")
                      (reminder_last_modified . "t1"))))
         (plan (org-rem-plan-reconciliation org-items reminders mappings)))
    (should (equal (plist-get plan :delete-reminders) '("RID-1")))))

(ert-deftest org-rem-plan-mapped-missing-reminder-deletes-org ()
  (let* ((org-items '((("org_id" . "ORG-1")
                       ("org_hash" . "h1"))))
         (reminders nil)
         (mappings '(((org_id . "ORG-1")
                      (org_hash . "h1")
                      (reminder_external_id . "RID-1")
                      (reminder_last_modified . "t1"))))
         (plan (org-rem-plan-reconciliation org-items reminders mappings)))
    (should (equal (plist-get plan :delete-org) '("ORG-1")))))

(ert-deftest org-rem-plan-conflict-org-wins-updates-reminder ()
  (let* ((org-items '((("org_id" . "ORG-1")
                       ("org_hash" . "h2"))))
         (reminders '((("external_id" . "RID-1")
                       ("last_modified" . "t2"))))
         (mappings '(((org_id . "ORG-1")
                      (org_hash . "h1")
                      (reminder_external_id . "RID-1")
                      (reminder_last_modified . "t1"))))
         (plan (org-rem-plan-reconciliation org-items reminders mappings)))
    (should (equal (plist-get plan :update-reminders)
                   '(("ORG-1" . "RID-1"))))
    (should (equal (plist-get plan :update-org) nil))))

(ert-deftest org-rem-plan-reminder-only-change-updates-org ()
  (let* ((org-items '((("org_id" . "ORG-1")
                       ("org_hash" . "h1"))))
         (reminders '((("external_id" . "RID-1")
                       ("last_modified" . "t2"))))
         (mappings '(((org_id . "ORG-1")
                      (org_hash . "h1")
                      (reminder_external_id . "RID-1")
                      (reminder_last_modified . "t1"))))
         (plan (org-rem-plan-reconciliation org-items reminders mappings)))
    (should (equal (plist-get plan :update-org)
                   '(("ORG-1" . "RID-1"))))))

(ert-deftest org-rem-plan-unmapped-items-create-on-opposite-side ()
  (let* ((org-items '((("org_id" . "ORG-NEW")
                       ("org_hash" . "h1"))))
         (reminders '((("external_id" . "RID-NEW")
                       ("last_modified" . "t1"))))
         (mappings nil)
         (plan (org-rem-plan-reconciliation org-items reminders mappings)))
    (should (equal (plist-get plan :create-reminders) '("ORG-NEW")))
    (should (equal (plist-get plan :create-org) '("RID-NEW")))))

(provide 'sync-merge-test)

;;; sync-merge-test.el ends here
